src/Entity/Car.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Car
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $model;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $carburant;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Marque", inversedBy="cars")
     */
    private $marque;


    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime(groups={"default"})
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime(groups={"default"})
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\DateTime(groups={"default"})
     */
    private $deleted_at;

    /**
     * Car constructor
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * @param mixed $model
     */
    public function setModel($model): void
    {
        $this->model = $model;
    }

    /**
     * @return mixed
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * @param mixed $color
     */
    public function setColor($color): void
    {
        $this->color = $color;
    }

    /**
     * @return mixed
     */
    public function getCarburant()
    {
        return $this->carburant;
    }

    /**
     * @param mixed $carburant
     */
    public function setCarburant($carburant): void
    {
        $this->carburant = $carburant;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     */
    public function setCreatedAt($created_at): void
    {
        $this->created_at = $created_at;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     */
    public function setUpdatedAt($updated_at): void
    {
        $this->updated_at = $updated_at;
    }

    /**
     * @return mixed
     */
    public function getMarque()
    {
        return $this->marque;
    }

    /**
     * @param mixed $marque
     */
    public function setMarque($marque): void
    {
        $this->marque = $marque;
    }

    /**
     * @return mixed
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * @param mixed $deleted_at
     */
    public function setDeletedAt($deleted_at): void
    {
        $this->deleted_at = $deleted_at;
    }

    /**
     * @ORM\PostUpdate
     */
    public function postUpdate()
    {
        $this->setUpdatedAt(new \DateTime());
    }

}

src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Car;
use App\Entity\Marque;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('model')
            ->add('color')
            ->add('carburant')
            ->add('marque', EntityType::class, [
                'class' => Marque::class,
                'choice_label' => 'name'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Form\CarType;
use App\Repository\CarRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/car")
 */
class CarController extends AbstractController
{
    /**
     * @Route("/", name="car_index", methods={"GET"})
     */
    public function index(CarRepository $carRepository): Response
    {
        return $this->render('car/index.html.twig', [
            'cars' => $carRepository->findAllCar(),
        ]);
    }

    /**
     * @Route("/new", name="car_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $car = new Car();
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($car);
            $entityManager->flush();

            return $this->redirectToRoute('car_index');
        }

        return $this->render('car/new.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="car_show", methods={"GET"})
     */
    public function show(Car $car): Response
    {
        return $this->render('car/show.html.twig', [
            'car' => $car,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="car_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Car $car): Response
    {
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $car->postUpdate();
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('car_index');
        }

        return $this->render('car/edit.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="car_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Car $car): Response
    {
        if ($this->isCsrfTokenValid('delete'.$car->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $car->setDeletedAt(new \DateTime());
            $entityManager->flush();
        }

        return $this->redirectToRoute('car_index');
    }
}

templates/car/_delete_form.html.twig
<form method="post" action="{{ path('car_delete', {'id': car.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ car.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/car/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form-car'}}) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary form-group">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/car/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Edit Car{% endblock %}
{% block page_breadcrumb %}{{ parent() }} <span> / edit car</span>{% endblock %}
{% block body %}
    <h1>Edit Car</h1>

    {{ include('car/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="btn-group-operations form-group">
        <a href="{{ path('car_index') }}" class="btn btn-default">back to list</a>

        {{ include('car/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/car/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Car index{% endblock %}
{% block page_breadcrumb %}{{ parent() }}{% endblock %}
{% block body %}
    <h1>List Of Cars</h1>

    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Model</th>
                <th>Marque</th>
                <th>Color</th>
                <th>Carburant</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for car in cars %}
            <tr>
                <td>{{ car.id }}</td>
                <td>{{ car.name }}</td>
                <td>{{ car.model }}</td>
                <td><b>{{ car.marque.name }}</b></td>
                <td>{{ car.color }}</td>
                <td>{{ car.carburant }}</td>
                <td>{{ car.createdAt ? car.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ car.updatedAt ? car.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('car_show', {'id': car.id}) }}" class="btn btn-default">show</a>
                    <a href="{{ path('car_edit', {'id': car.id}) }}" class="btn btn-warning">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('car_new') }}" class="btn btn-primary">Create new car</a>
{% endblock %}

templates/car/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}New Car{% endblock %}
{% block page_breadcrumb %}{{ parent() }} <span> / create new car</span>{% endblock %}
{% block body %}
    <h1>Create new Car</h1>

    {{ include('car/_form.html.twig') }}

    <div class="form-group btn-group">
        <a href="{{ path('car_index') }}" class="btn btn-success ">back to list</a>
    </div>
{% endblock %}

templates/car/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Car{% endblock %}
{% block page_breadcrumb %}{{ parent() }} <span> / car detail</span>{% endblock %}
{% block body %}
    <h1>Car</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ car.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ car.name }}</td>
            </tr>
            <tr>
                <th>Model</th>
                <td>{{ car.model }}</td>
            </tr>
            <tr>
                <th>Color</th>
                <td>{{ car.color }}</td>
            </tr>
            <tr>
                <th>Carburant</th>
                <td>{{ car.carburant }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td><b>{{ car.marque.name }}</b></td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ car.createdAt ? car.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ car.updatedAt ? car.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>
    <div class="btn-group-operations form-group">
        <a href="{{ path('car_index') }}" class="btn btn-default">back to list</a>

        <a href="{{ path('car_edit', {'id': car.id}) }}" class="btn btn-warning">edit</a>

        {{ include('car/_delete_form.html.twig') }}
    </div>
{% endblock %}